\ TLISP.F (Win32Forth)
\
\ READ-LINE funktioniert nur mit DOS-Zeilenenden (CRLF), nicht mit UNIX-LFs

: U>= 2DUP = -ROT U> OR ;

SYS-WARNING-OFF
: [IFDEF]   DEFINED NIP 0= IF POSTPONE [ELSE] THEN ; IMMEDIATE
: [IFUNDEF] DEFINED NIP    IF POSTPONE [ELSE] THEN ; IMMEDIATE

FLOAD TLISP.FS
