(PUTPROP 'DEFLIST
	(LAMBDA (X Y) ())
	EXPR)

(DEFLIST '((DEFINE (LAMBDA (X)   (DEFINE X EXPR)))
          ((CSET   (LAMBDA (X Y) (PUTPROP X Y APVAL))))))

(DEFINE '((DEF (LAMBDA (FN PL FORM)
		(DEFINE (LIST (LIST FN
				(LIST LAMBDA PL FORM)
		)))
	))))
