; usage: "submit tlisp ..\" (Windows)
;        "submit tlisp ../" (Linux)
;
;xsub
;
; change file attributes to r/w
stat *.blk    $$r/w
stat *.f83    $$r/w
stat *.lsp    $$r/w
stat tlisp.fs $$r/w
;
; copy files from host
r $1*.blk    l
r $1*.f83    l
r $1*.lsp    l
r $1tlisp.fs l
;
; change file attributes to r/o
stat *.blk    $$r/o
stat *.f83    $$r/o
stat *.lsp    $$r/o
stat tlisp.fs $$r/o
;
b:f83
;open tfload.blk 2 load
;open eaker.f83 tfload
;open ans.f83 tfload
